export {default} from "./App";
export { AccountsManagement } from "./components/AccountsManagement"
export { AdmissionManagement } from "./components/AdmissionManagement"
export { ConsultationManagement } from "./components/ConsultationManagement"
export {CreateIP } from "./components/CreateIP"
export { ExpenseIncome} from "./components/ExpenseIncome"
export { FinancialCharts} from "./components/FinancialCharts"
export { IPCreation} from "./components/IPCreation"
export { IPPDFDocument} from "./components/IPPDFDocument"
export { OPPDFDocument } from "./components/JImsOP-PDF-Template"
export { JamalOP} from "./components/JamalOP"
export { JimsOP} from "./components/JimsOP"
export { MedicalHistory} from "./components/MedicalHistory"
export { OPCreation} from "./components/OPCreattion"
// export { OPPDFDocument} from "./components/OPPDFTemplate"
export { PatientList} from "./components/PatientList"
export { PatientManagement} from "./components/PatientManagement"
export { PatientRegistration} from "./components/PatientRegistration"
export * from "../../apiClient/apiclient"
